export enum AssistantAdviceStatus {
    NO_ADVICE_NEEDED = 'NO_ADVICE_NEEDED',
    WAITING_FOR_GOLDEN_BALLS_DECLARATION_ADVICE = 'WAITING_FOR_GOLDEN_BALLS_DECLARATION_ADVICE',
    WAITING_FOR_USER_TO_KICK_ADVICE = 'WAITING_FOR_USER_TO_KICK_ADVICE',
}
