export enum PlayerStates {
    END_SPLIT_OR_STEAL = 'END_SPLIT_OR_STEAL',
    IN_GAME = 'IN_GAME',
    IN_GOLDEN_BALLS_ROUND = 'IN_GOLDEN_BALLS_ROUND',
    IN_SPLIT_OR_STEAL = 'IN_SPLIT_OR_STEAL',
    NOT_IN_GAME = 'NOT_IN_GAME',
    PREPARING_GOLDEN_BALLS = 'PREPARING_GOLDEN_BALLS',
    PREPARING_SPLIT_OR_STEAL = 'PREPARING_SPLIT_OR_STEAL',
    SEARCHING_FOR_GAME = 'SEARCHING_FOR_GAME',
    WAITING_FOR_GOLDEN_BALLS = 'WAITING_FOR_GOLDEN_BALLS',
}
